services:
  - type: web
    name: u7buy-webhook
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_WEBHOOK
        sync: false
      - key: GAMEFLIP_API_KEY
        sync: false
      - key: GAMEFLIP_TOTP_SECRET
        sync: false
      - key: GAMEFLIP_CHANNEL_WEBHOOKS
        sync: false
      - key: DISCORD_MENTION_USER_ID_U7BUY
        sync: false
      - key: DISCORD_MENTION_USER_ID_GAMEFLIP
        sync: false
